
version: "3"
services:
  postgres:
    ports:
      - ${PSQL_PORTS}
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PRISMA_USERNAME}
      POSTGRES_PASSWORD: ${PRISMA_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORTS}
  # redis-commander:
  #   container_name: redis-commander
  #   hostname: redis-commander
  #   image: rediscommander/redis-commander:latest
  #   restart: always
  #   environment:
  #     - REDIS_HOSTS=local:redis:${REDIS_PORT}:${REDIS_PASSWORD}
  #   ports:
  #     - "8084:8084"
volumes:
  postgres:
  redis-data:
